// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH3sOGWWbNQ-aZwJ8UWgH4hs5zbgf1DAI',
    appId: '1:598157817700:android:5273a4eb430ed48c08ac71',
    messagingSenderId: '598157817700',
    projectId: 'localme-7f20e',
    storageBucket: 'localme-7f20e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqTZ57Kuj2tP5y-j5d_2bbcf97wx1q8yU',
    appId: '1:598157817700:ios:2b8b79ec2d03b69508ac71',
    messagingSenderId: '598157817700',
    projectId: 'localme-7f20e',
    storageBucket: 'localme-7f20e.appspot.com',
    iosClientId: '598157817700-q1p7he22u4ck4bbiha0na48st5vb9qpm.apps.googleusercontent.com',
    iosBundleId: 'info.localme.localmeapp',
  );
}
